In [1]:
# numpyをimport。
import numpy as np

# 行列AとBを作成。
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# AとBの積を求めて出力。
C = np.dot(A, B)
print(C)

# Cの要素の最大値を求める。
C.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


np.int64(47)